CREATE TABLE tasks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    content TEXT,
    date_modified TIMESTAMPTZ DEFAULT now() NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
    date_due TIMESTAMPTZ DEFAULT (now() + interval '1 day 2 hours 30 minutes')
);
